import { Product } from './types';

export const PRODUCTS_DATA: Product[] = [
  // --- original Reera Keys & Buttons (keys) ---
  {
    id: 'AB328',
    title: 'کلید بازکن درب صندوق ریرا مدل AB328',
    titleEn: 'Reera Tailgate Opener Switch AB328',
    model: 'AB328',
    category: 'keys',
    categoryFa: 'کلید ها',
    categoryEn: 'Keys & Buttons',
    description: 'این کلید مدرن ارگونومیک به طور ویژه برای باز کردن برقی درب صندوق عقب خودروی ملی ریرا طراحی شده است. بهره‌گیری از میکروسوئیچ حساس با کلیدزنی نرم، طول عمر بالا و پس‌زمینه یکپارچه شب‌نما از ویژگی‌های بارز این محصول می‌باشد.',
    descriptionEn: 'This modern ergonomic button is specifically designed for the electric trunk opener of the Reera national crossover. It features a high-sensitivity microswitch, smooth tactile clicks, extended lifecycle, and integrated night-glow LED backlight.',
    features: [
      'سازگاری کامل با پروتکل مالتی‌پلکس کابین ریرا',
      'بک‌لایت یکنواخت قرمز با دیودهای LED بادوام',
      'بیش از ۱۰۰,۰۰۰ سیکل کاری مکانیکی و الکتریکی تضمین‌شده',
      'بدنه از جنس ABS/PC ضد خش و مقاوم در برابر نور خورشید',
    ],
    featuresEn: [
      'Full compatibility with Reera cockpit multiplex protocols',
      'Uniform red backlight using premium durable LEDs',
      'Over 100,000 guaranteed mechanical and electrical cycles',
      'Body made of scratch-resistant and UV-resistant ABS/PC polymer',
    ],
    specs: {
      'ولتاژ کاری': '۹ الی ۱۶ ولت DC',
      'جریان عبوری نامی': 'حداکثر ۱۰۰ میلی‌آمپر',
      'مقاومت عایقی': 'بیش از ۱۰۰ مگا اهم',
      'محدوده دمای عملکرد': '-۴۰ تا +۸۵ درجه سانتی‌گراد',
      'استاندارد تست': 'PSA B21 7050',
    },
    specsEn: {
      'Working Voltage': '9 to 16V DC',
      'Rated Current': 'Max 100mA',
      'Insulation Resistance': 'Over 100 MOhm',
      'Operating Temperature': '-40 to +85 °C',
      'Test Standard': 'PSA B21 7050',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB328-1-270x262.jpg',
  },
  {
    id: 'AB327',
    title: 'کلید ترمز پارک برقی و اتوهلد ریرا مدل AB327',
    titleEn: 'Reera EPB & Auto-Hold Console Switch AB327',
    model: 'AB327',
    category: 'keys',
    categoryFa: 'کلید ها',
    categoryEn: 'Keys & Buttons',
    description: 'کلید ترمز پارک برقی (EPB) و سیستم نگهدارنده اتوماتیک (Auto-Hold) خودرو ریرا. طراحی فوق‌العاده ظریف این کلید دوحالته، امنیت پارک را با بازخورد لمسی مناسب و سیستم قفل دوگانه سخت‌افزاری تضمین می‌کند.',
    descriptionEn: 'Electric Parking Brake (EPB) and Automatic Vehicle Hold (Auto-Hold) console control for Reera. The premium dual-state lever ensures parking safety with realistic haptic clicks and secondary hardware locking checks.',
    features: [
      'سیستم فرمان دوگانه ایمن جهت جلوگیری از فعال‌سازی تصادفی',
      'نورپردازی دورنگ متغیر جهت نمایش وضعیت فعال/غیرفعال بودن اتوهلد',
      'کانکتور طلاکاری شده برای هدایت الکتریکی فوق‌العاده و عدم افت ولتاژ',
      'مقاومت کامل در برابر ریزش مایعات روی کنسول مرکزی',
    ],
    featuresEn: [
      'Dual-command safety linkage to prevent accidental triggers',
      'Dynamic dual-color LED backlight showing status (Active/Inactive)',
      'Gold-plated pins for excellent electrical conductivity and low signal drop',
      'High resistance to liquid spills on the central gear console',
    ],
    specs: {
      'نوع پین‌ها': 'کانکتور ۸ پین آبکاری طلا',
      'سیستم ارتباطی': 'لینک مستقیم به ECU ترمز پارک برقی',
      'عمر کلیدزنی': '۲۰۰,۰۰۰ سیکل ترمز پارک / ۱۰۰,۰۰۰ سیکل اتوهلد',
      'درجه آب‌بندی': 'IP52 (محافظت در برابر نفوذ گرد و غبار و رطوبت)',
    },
    specsEn: {
      'Pin Configuration': 'Gold-Plated 8-Pin Connector',
      'Interface Protocol': 'Direct Link to EPB ECU Unit',
      'Actuation Lifespan': '200,000 EPB cycles / 100,000 Auto-Hold cycles',
      'Ingress Protection': 'IP52 (Dust & Moisture Shield)',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB327-1-270x262.jpg',
  },
  {
    id: 'AB326',
    title: 'کلید فلاشر ریرا مدل AB326',
    titleEn: 'Reera Hazard Flasher Switch AB326',
    model: 'AB326',
    category: 'keys',
    categoryFa: 'کلید ها',
    categoryEn: 'Keys & Buttons',
    description: 'کلید هشدار خطر (فلاشر) کنسول مرکزی ریرا. این کلید با طراحی مثلثی نمادین با بک‌لایت قرمز تند جهت جلب توجه راننده در شرایط اضطراری طراحی شده است. دارای مکانیزم قفل شونده با ضربه ملایم زدن.',
    descriptionEn: 'Hazard alert (flasher) warning button for the center dashboard. It features an iconic red triangle sign with bright backlight to catch driver attention in emergencies, powered by double-action push locks.',
    features: [
      'رنگ‌آمیزی با کیفیت لیزری کلید جهت وضوح کامل آیکون هشدار در روز و شب',
      'مکانیزم دابل-اکشن جهت بازخورد سریع به راننده در شرایط اورژانسی',
      'طول عمر بالا متناسب با استانداردهای بین‌المللی ایمنی خودرو',
      'طراحی هماهنگ با دیزاین یکپارچه داشبورد',
    ],
    featuresEn: [
      'Precise laser-etched icon for excellent night readability',
      'Double-action mechanism for immediate click-and-hold activation',
      'Extended service life satisfying highest international safety regulations',
      'Seamless aesthetic alignment with center dash paneling',
    ],
    specs: {
      'رنگ بدنه': 'مشکی مات پیانویی با آیکون شفاف سفید',
      'ولتاژ عملکرد': '۱۲ ولت نامی',
      'جریان اتصال کوتاه حداکثر': '۵ آمپر',
      'تست ضربه': 'تست سقوط از ارتفاع ۱ متری روی سطح سخت',
    },
    specsEn: {
      'Body Color': 'Piano Matte Black with translucent icon',
      'Operating Voltage': '12V Nominal',
      'Short Circuit Current': 'Max 5A',
      'Drop Test': 'Sustained 1-meter drop test on steel surface',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB326-1-270x262.jpg',
  },
  {
    id: 'AB325',
    title: 'کلید مرکزی داشبورد ریرا مدل AB325',
    titleEn: 'Reera Dash Multi-Switch Module AB325',
    model: 'AB325',
    category: 'keys',
    categoryFa: 'کلید ها',
    categoryEn: 'Keys & Buttons',
    description: 'مجموعه کلیدهای مالتی‌فانکشن مرکزی روی داشبورد ریرا جهت کنترل سیستم‌های رفاهی، قفل مرکزی درب‌ها، گرمکن شیشه عقب و تهویه مطبوع. تجمیع کلیدها در یک یونیت، شلوغی سیم‌کشی کابین را به حداقل رسانده است.',
    descriptionEn: 'Integrated dash multi-function panel controlling door locks, rear glass heaters, ESP toggles, and air vents. Combining multiple buttons into a single smart unit minimizes interior wiring complexity.',
    features: [
      'ادغام کلیدهای چندگانه در یک ماژول الکترونیکی متمرکز',
      'سیم‌کشی بهینه از طریق پورت باس مشترک جهت ارتباط با BCM',
      'طراحی فوق‌العاده لوکس هماهنگ با نمای مرکزی داشبورد ریرا',
      'کلیدزنی بسیار دقیق با صدای ملایم و لوکس',
    ],
    featuresEn: [
      'Consolidation of 5 independent keys in one hardware module',
      'Optimized digital data transmission to BCM using LIN bus link',
      'Luxurious outer panel designed for high-end vehicle cockpits',
      'Smooth switch travel with ultra-low clicking noise',
    ],
    specs: {
      'پروتکل ارتباطی': 'شبکه LIN Bus',
      'تعداد سوییچ‌های ادغام شده': '۵ عدد سوئیچ مستقل',
      'ولتاژ منبع تغذیه': '۹ تا ۱۸ ولت DC',
      'جریان استندبای': 'کمتر از ۱ میلی‌آمپر',
    },
    specsEn: {
      'Communication': 'LIN Bus Protocol',
      'Button Elements': '5 Independent tactile switches',
      'Supply Voltage': '9V to 18V DC',
      'Standby Current': 'Less than 1mA',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB325-1-270x262.jpg',
  },
  {
    id: 'AB330',
    title: 'کلید کنترل گیربکس ریرا مدل AB330',
    titleEn: 'Reera Electronic Gear Shifter Panel AB330',
    model: 'AB330',
    category: 'keys',
    categoryFa: 'کلید ها',
    categoryEn: 'Keys & Buttons',
    description: 'ماژول انتخابگر وضعیت دنده (شایفتر گیربکس برقی) خودرو ریرا. این قطعه های‌تک به راننده اجازه می‌دهد تا حالت‌های رانندگی (Drive, Reverse, Neutral, Park) و حالت اسپرت/برفی را با ایمنی و روانی کامل انتخاب کند.',
    descriptionEn: 'Electric gear selector panel (Shift-by-Wire shifter) for Reera. This advanced automotive module transmits gear positions (D, R, N, P) and drive modes (Sport/Snow) with utmost speed and strict interlocking safety.',
    features: [
      'مکانیزم قفل ایمنی سولنوئیدی الکترومکانیکی جهت عدم شیفت ناخواسته',
      'فیدبک نوری LED رنگی متمایز برای هر موقعیت دنده',
      'انتقال وضعیت دنده به صورت کاملاً الکترونیکی (Shift-by-Wire)',
      'ظاهر لوکس با تلفیق مشکی براق و کروم نقره‌ای مقاوم در برابر فرسایش دستان',
    ],
    featuresEn: [
      'Active solenoid-driven mechanical lock to prevent illegal shift states',
      'Differentiated multi-color LED backlighting for active gears',
      'High-reliability Shift-by-Wire electronic transmission link',
      'Stellar piano-black chrome finishing resistant to hand sweat and friction',
    ],
    specs: {
      'ارتباط با گیربکس': 'شبکه CAN Bus سرعت بالا (High Speed)',
      'سیستم قفل دنده': 'مجهز به مکانیزم مگنت سولنوئید داخلی فعال',
      'دمای تست انبارش': '-۴۵ تا +۹۵ درجه سانتی‌گراد',
      'مکانیزم ایمنی': 'هماهنگ با سنسور فشار پدال ترمز خودرو',
    },
    specsEn: {
      'Bus Communication': 'High-Speed CAN Bus Interface',
      'Interlock Unit': 'Internal active Solenoid Magnet Assembly',
      'Storage Temp Test': '-45 to +95 °C',
      'Safety Compliance': 'Synced with brake pedal pressure telemetry',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB330-1-270x262.jpg',
  },

  // --- Category: others (استپر موتورها و ...) ---
  {
    id: 'AB282',
    title: 'استپر موتور XU7 مدل AB282',
    titleEn: 'Stepper Motor XU7 AB282',
    model: 'AB282',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'استپر موتور (شیر کنترل هوای دور آرام) مخصوص موتورهای XU7 با شفت فلزی دقیق و استهلاک ناچیز. تنظیم دقیق میزان هوای ورودی در زمان درجا کار کردن موتور جهت جلوگیری از خاموشی موتور در بار سنگین.',
    descriptionEn: 'High-precision Idle Air Control (IAC) stepper motor for XU7 engines. It ensures reliable and smooth idle RPM control under cold starts, heavy electrical loads, and air conditioning compressor engagement.',
    features: [
      'مجهز به موتور پله‌ای دقیق با رزولوشن میکرومتری',
      'بدنه برنجی و مقاوم در برابر گازهای خروجی کارتل',
      'طول عمر مکانیکی و پایداری عملکرد در دمای بالا',
    ],
    featuresEn: [
      'High-precision micro-step resolution for stable air metering',
      'Durable brass shaft resistant to oil vapors and engine backfires',
      'Tested to withstand engine vibration and ambient heat up to 130°C',
    ],
    specs: {
      'موتور خودروی هدف': 'پژو ۴۰۵، پارس و سمند با موتور XU7',
      'تعداد پله‌ها': 'حداکثر ۲۵۰ پله',
      'پین‌های کانکتور': '۴ پین تخت هماهنگ با استانداردهای ایران خودرو',
    },
    specsEn: {
      'Compatible Engines': 'Peugeot 405, Pars, Samand (XU7)',
      'Total Steps': 'Max 250 steps',
      'Terminal Connector': '4-Pin flat harness slot',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB282-1-270x262.jpg',
  },
  {
    id: 'AB333',
    title: 'استپر موتور مدل AB333',
    titleEn: 'Stepper Motor AB333',
    model: 'AB333',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'استپر موتور نسل جدید با پاسخ فرکانسی سریع‌تر جهت پایش و تنظیم هوای دور درجا موتور با بازخورد هیدرولیک و ضربه پذیری کامل.',
    descriptionEn: 'Next-generation idle air control stepper motor featuring accelerated transient response and supreme durability against manifold backpressure.',
    features: [
      'تراش‌کاری و پرداخت تمام فولادی قطعات متحرک داخلی',
      'ایزولاسیون کامل سیم‌پیچ‌های الکترومغناطیسی با رزین فشرده',
      'جلوگیری تضمینی از نوسان دور موتور (Idle Fluctuations)',
    ],
    featuresEn: [
      'Ultra-fine CNC-machined stainless steel plunger mechanism',
      'Resin-encapsulated coils resistant to vibration and humidity',
      'Prevents idle hunting and sudden RPM drops under load',
    ],
    specs: {
      'جریان عبوری سیم‌پیچ': 'حداکثر ۴۵۰ میلی‌آمپر',
      'درجه آب‌بندی شفت': 'روکش سیلیکونی محافظ',
      'ولتاژ تحریک پله': '۱۲ ولت DC',
    },
    specsEn: {
      'Coil Drive Current': 'Max 450mA',
      'Shaft Dust Cover': 'High-grade protective silicon dust boot',
      'Coil Nominal Voltage': '12V DC',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB314-1-270x262.jpg',
  },

  // --- Category: switches (سوئیچ‌ها و ترموسوئیچ‌ها) ---
  {
    id: 'AB222',
    title: 'ترموسوئیچ قطع کن فن رادیات مدل AB222',
    titleEn: 'Radiator Fan Cut-Off Thermoswitch AB222',
    model: 'AB222',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'سوئیچ دمایی (ترموسوئیچ) قطع و وصل فن رادیاتور خودرو مدل AB222 با حساسیت حرارتی استثنایی بایل-متال. حفاظت مطمئن از دمای کاری موتور جهت به حداقل رساندن خطر سوختن واشر سرسیلندر.',
    descriptionEn: 'High-sensitivity bimetallic thermoswitch designed to regulate radiator cooling fan activation based on real-time coolant temperatures, ensuring maximum head gasket protection.',
    features: [
      'کنتاکت‌های دوبل با آلیاژ مس-نقره جهت ممانعت از جرقه زدن و فرسودگی',
      'پوشش برنجی سنگین با رسانایی حرارتی بسیار بالا',
      'آب‌بندی ۱۰۰٪ با رزوه استاندارد فلزی',
    ],
    featuresEn: [
      'Copper-silver alloy switch contacts preventing high-current arcing',
      'Solid heavy brass housing for instant heat transfer from coolant',
      'Hermetically sealed design with precise BSP thread locking',
    ],
    specs: {
      'دمای قطع نامی': '۸۸ درجه سانتی‌گراد',
      'دمای وصل مجدد': '۸۳ درجه سانتی‌گراد',
      'جریان الکتریکی کاری': 'حداکثر ۱۶ آمپر در ۱۲ ولت دیسی',
    },
    specsEn: {
      'Nominal Opening Temp': '88 °C',
      'Nominal Closing Temp': '83 °C',
      'Maximum Ampere Load': '16A / 12V DC',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB222-1-270x262.jpg',
  },
  {
    id: 'AB003',
    title: 'سوئیچ چراغ ترمز دستی و صندوق عقب مدل AB003',
    titleEn: 'Handbrake & Trunk Lamp Switch AB003',
    model: 'AB003',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'سوئیچ الکترومکانیکی فشاری (شاسی لای‌دری) جهت روشن ساختن چراغ داخل صندوق عقب و همچنین نمایش وضعیت ترمز دستی در صفحه کیلومتر خودرو با مقاومت در برابر زنگ زدگی و ضربه.',
    descriptionEn: 'Heavy-duty tactile pin-switch for car trunks and handbrake levers. Sends quick signals to cabin lights and cluster warning lamps with high resistance to oxidation.',
    features: [
      'بدنه پلیمری تقویت‌شده و نشکن با پین فشاری خودتنظیم',
      'لاستیک محافظ گردگیر آب‌بند هماهنگ با شرایط اقلیمی مرطوب',
      'اتصال آسان سوکت الکتریکی با پین برنجی آبکاری شده',
    ],
    featuresEn: [
      'Impact-resistant compound body with self-adjusting haptic plunger',
      'EPDM rubber dust cover to protect the contacts from mud and moisture',
      'Corrosion-free electroplated brass tab terminals for stable electrical connection',
    ],
    specs: {
      'جریان اتصال نامی': '۵ آمپر',
      'تست دوام فشرده شدن': 'بیش از ۳۰۰,۰۰۰ سیکل بی نقص',
      'نوع کنتاکت': 'تک فیش اتصال بدنه (Single-pole grounding)',
    },
    specsEn: {
      'Rated Current Load': '5 Amps',
      'Durability Test': 'Sustained over 300,000 cyclic push impacts',
      'Contact Architecture': 'Single-pole chassis-grounding circuit',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/02/AB003-270x262.jpg',
  },
  {
    id: 'AB001',
    title: 'سوئیچ چراغ ترمز مدل AB001',
    titleEn: 'Stop Light Switch AB001',
    model: 'AB001',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'سوئیچ الکتریکی استپ ترمز دو فیش متصل به بازوی پدال ترمز. فعال‌سازی فوری چراغ‌های هشدار عقب خودرو به محض لمس پدال ترمز جهت مطلع ساختن رانندگان پشتی.',
    descriptionEn: 'Automotive 2-Pin brake light switch. Triggers rear brake light bulbs immediately upon pedal depression to prevent rear-end collisions.',
    features: [
      'فنر بازگردان مستحکم استنلس استیل جهت واکنش آنی پین',
      'کنتاکت‌های داخلی مقاوم با روکش نقره نیکل',
      'نصب بسیار سریع و آسان بر روی براکت فرمان',
    ],
    featuresEn: [
      'Robust stainless steel internal spring for instant return action',
      'Silver-nickel plated copper alloy contacts to resist thermal wear',
      'Simple twist-lock design for speedy assembly on steering brackets',
    ],
    specs: {
      'ولتاژ نامی': '۱۲ ولت DC',
      'جریان خروجی': '۱۰ آمپر',
      'طول عمر فشرده‌سازی': '۵۰۰,۰۰۰ سیکل کارکرد',
    },
    specsEn: {
      'Nominal Voltage': '12V DC',
      'Continuous Rating': '10 Amps',
      'Toggling Durability': '500,000 cycles',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB001-1-270x262.jpg',
  },
  {
    id: 'AB004',
    title: 'سوئیچ چراغ ترمز مدل AB004',
    titleEn: 'Stop Light Switch AB004',
    model: 'AB004',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'سوئیچ استپ ترمز پدالی چهار فیش مجهز به دو کنتاکت مستقل. علاوه بر روشن کردن چراغ ترمز عقب، سیگنال همزمانی به ECU موتور جهت غیرفعال کردن موقت کروز کنترل و ترمز برقی ارسال می‌کند.',
    descriptionEn: 'Multi-circuit 4-Pin stop light switch. Features separate contacts for signaling the rear brake lamps and disengaging Cruise Control or updating the vehicle safety systems.',
    features: [
      'کنتاکت دوبل همزمان (Normally Open + Normally Closed)',
      'بدنه ساخته شده از پلی‌آمید ۶۶ با ۳۰ درصد الیاف شیشه',
      'مقاومت عالی در برابر سایش در استفاده‌های مکرر ترافیکی',
    ],
    featuresEn: [
      'Dual synchronized contacts (NO + NC) for brakes and computer telemetry',
      'Fiberglass reinforced PA66 engineering plastic housing for stiffness',
      'Designed to endure massive cycles in daily urban stop-and-go driving',
    ],
    specs: {
      'جریان عبوری': 'حداکثر ۱۲ آمپر در ۱۲ ولت دیسی',
      'نوع کانکتور': '۴ پین تخت مجهز',
      'دامنه دمای مجاز': '-۴۰ تا +۹۰ درجه سانتی‌گراد',
    },
    specsEn: {
      'Current Draw': 'Max 12A / 12V DC',
      'Connector Socket': '4-Pin flat harness slot',
      'Thermal Tolerance': '-40 to +90 °C',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB004-1-270x262.jpg',
  },
  {
    id: 'AB002',
    title: 'سوئیچ چراغ دنده عقب مدل AB002',
    titleEn: 'Reverse Light Switch AB002',
    model: 'AB002',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'فشنگی دنده عقب گیربکس مدل AB002. این قطعه بر روی پوسته گیربکس نصب شده و وظیفه روشن ساختن چراغ‌های دنده عقب را در ثانیه‌ای که دنده در حالت عقب قرار می‌گیرد بر عهده دارد.',
    descriptionEn: 'High-current reverse gear light switch installed directly on the transmission casing. Triggers rear back-up lights with zero delay upon engaging the reverse gear.',
    features: [
      'آب‌بندی کامل رزوه با آلیاژ فلزی یکپارچه جهت ممانعت از نشت واسکازین',
      'کنتاکت‌های برنجی ویژه با روکش نیکل جهت دوام اتصال برقی',
      'مقاوم در برابر تکان‌های شدید گیربکس',
    ],
    featuresEn: [
      'Leak-free single-body brass threads prevent transmission oil seepage',
      'Nickel-plated copper contacts maintain low electrical resistance over time',
      'Sustains heavy high-frequency vibrations in the gearbox mounting area',
    ],
    specs: {
      'سایز رزوه': 'M12 x 1.5',
      'ولتاژ کاری': '۱۲ ولت DC',
      'حداکثر جریان': '۸ آمپر',
    },
    specsEn: {
      'Thread Dimensions': 'M12 x 1.5',
      'Voltage Spec': '12V DC Nominal',
      'Max Amperage': '8A',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB002-1-1-270x262.jpg',
  },
  {
    id: 'AB013',
    title: 'سوئیچ چراغ دنده عقب مدل AB013',
    titleEn: 'Reverse Light Switch AB013',
    model: 'AB013',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'فشنگی سوئیچ دنده عقب تقویت‌شده مدل AB013 با راندمان مکانیکی بالا و پین تماسی سخت‌کاری شده جهت استفاده در سخت‌ترین شرایط گیربکسی.',
    descriptionEn: 'Reinforced reverse gear switch featuring a hardened spring-loaded ball plunger to sustain extreme shifting forces in heavy gearboxes.',
    features: [
      'ساختار فلزی مستحکم با روکش ضد زنگ الکترولیز',
      'آب‌بندی اورینگ ویتون بسیار بادوام و مقاوم به ترکیبات نفتی واسکازین',
      'پاسخ تماسی مطمئن حتی با فشار حداقلی بازوی دنده',
    ],
    featuresEn: [
      'Solid steel construction with defensive anti-corrosive electroplating',
      'Viton O-ring seals designed to endure chemically aggressive gear lubricants',
      'Guarantees electrical latching even with subtle mechanical shift tolerances',
    ],
    specs: {
      'رزوه نصب': 'M14 x 1.5',
      'جریان اتصال نامی': '۱۰ آمپر',
      'طول عمر مکانیکی': '۴۰۰,۰۰۰ سیکل تغییر دنده',
    },
    specsEn: {
      'Mounting Thread': 'M14 x 1.5',
      'Switch Rating': '10 Amps',
      'Mechanical Endurance': '400,000 shifting engagement cycles',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB013-2-270x262.jpg',
  },
  {
    id: 'AB027',
    title: 'سوئیچ چراغ دنده عقب مدل AB027',
    titleEn: 'Reverse Light Switch AB027',
    model: 'AB027',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'فشنگی چراغ دنده عقب گیربکس اتومبیل مدل AB027 با پورت اتصال سریع (Quick-Connect) و عایق کامل در برابر پاشش گل و لای کف جاده.',
    descriptionEn: 'Automotive reverse lamp switch featuring a robust quick-connect socket layout, preventing dust, water, and road grime from reaching electrical connections.',
    features: [
      'کانکتور پلاستیکی عایق با خار قفل‌شونده برای اطمینان اتصالات برقی',
      'پین فشاری هگز ضخیم جهت سهولت در بستن با آچار بوکس',
      'طراحی مطابق با استانداردهای نوین زنجیره تامین قطعات خودروسازی',
    ],
    featuresEn: [
      'Sealed quick-connect housing with integrated dual retaining clips',
      'Rugged hexagonal collar for quick installation with power sockets',
      'Manufactured to meet the strict quality standards of top OEMs',
    ],
    specs: {
      'جنس رزوه': 'آلیاژ فلزی فولاد کربنی سخت‌کاری شده',
      'تست مقاومت نمکی': 'بیش از ۹۶ ساعت تست Salt Spray بی نقص',
      'جریان مجاز عبوری': '۶ آمپر روی ۱۲ ولت دیسی',
    },
    specsEn: {
      'Thread Material': 'Heat-treated carbon steel alloy',
      'Salt Spray Test': 'Withstands 96-hour continuous salt spray chamber test',
      'Nominal Current': '6A / 12V DC',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB027-1-270x262.jpg',
  },
  {
    id: 'AB052',
    title: 'سوئیچ چراغ دنده عقب مدل AB052',
    titleEn: 'Reverse Light Switch AB052',
    model: 'AB052',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'فشنگی دنده عقب دابل-آب‌بند مدل AB052. مقاومت کامل در برابر روغن گیربکس داغ و انتقال فیدبک برقی بدون وقفه به سیستم سنسورهای کمکی پارک عقب خودرو.',
    descriptionEn: 'Double-sealed reverse switch. Specially formulated to resist boiling-hot gear oils while delivering uninterrupted signals to backup cameras and rear ultrasonic parking modules.',
    features: [
      'واشر آب‌بندی داخلی دوبل ویتون با مقاومت در برابر خورندگی شیمیایی روغن',
      'پین‌های داخلی نقره کبالت ضد جرقه',
      'سازگاری با دامنه وسیع ولتاژهای ۹ الی ۱۸ ولت دیسی',
    ],
    featuresEn: [
      'Double Viton internal seals prevent high-pressure oil bypass leaks',
      'Spark-suppressed silver-cobalt internal contact buttons',
      'Compatible with broad automotive electrical grids from 9 to 18V DC',
    ],
    specs: {
      'سایز رزوه': 'M12 x 1.25',
      'مقاومت عایقی بدنه': 'بیش از ۱۵۰ مگا اهم در ۵۰۰ ولت',
      'فشار هیدرولیک تحمل': 'تا ۱۵ بار بدون دفرمه شدن',
    },
    specsEn: {
      'Thread Specification': 'M12 x 1.25',
      'Dielectric Insulation': 'Over 150 MOhm at 500V test',
      'Hydrostatic Rating': 'Withstands 15 bar backpressure without structural distortion',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB052-1-270x262.jpg',
  },
  {
    id: 'AB227',
    title: 'سوئیچ چراغ دنده عقب مدل AB227',
    titleEn: 'Reverse Light Switch AB227',
    model: 'AB227',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'سوئیچ الکتریکی دنده عقب مدل AB227. این فشنگی به صورت کاملاً هرمتیک آب‌بندی شده و با پین ماشه‌ای کروی نرم، حرکت بسیار روان و سریع دنده‌ها را پایش می‌کند.',
    descriptionEn: 'High-durability reverse light switch AB227. Hermetically sealed trigger switch with a ball-plunger configuration designed for effortless and silent mechanical shifting tracking.',
    features: [
      'مکانیزم ماشه کروی (Ball Plunger) سخت‌کاری شده جهت کاهش استهلاک گیربکس',
      'کانکتور یکپارچه مقاوم به شوک‌های فیزیکی شدید',
      'حداقل لرزش پین تماسی به دلیل طراحی فنر بهینه',
    ],
    featuresEn: [
      'Ball-plunger actuator minimizes shift fork drag and physical wear',
      'Molded terminal housing protects pins from vibration and road impacts',
      'Incredibly stable contact pressure prevents flickering tail lights',
    ],
    specs: {
      'ولتاژ عملکرد': '۱۲ ولت DC',
      'جریان عبوری کاری': 'حداکثر ۱۰ آمپر دیسی',
      'درجه محافظت کانکتور': 'IP67 ضدآب کامل',
    },
    specsEn: {
      'Operating Voltage': '12V DC',
      'Rated Current Limit': 'Max 10A DC',
      'Ingress Protection': 'IP67 waterproof rating',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB227-1-270x262.jpg',
  },
  {
    id: 'AB253',
    title: 'سوئیچ چراغ دنده عقب مدل AB253',
    titleEn: 'Reverse Light Switch AB253',
    model: 'AB253',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'فشنگی و سوئیچ تماسی دنده عقب خودرو مدل AB253 مخصوص جعبه دنده‌های هماهنگ شده فرانسوی و ملی با پاسخ‌دهی آنی.',
    descriptionEn: 'Highly responsive reverse gear sensor switch AB253, specifically designed for national and French manual transmissions.',
    features: [
      'پایداری فوق‌العاده کنتاکت‌های برقی در نوسانات شدید ولتاژ دینام',
      'بدنه ساخته شده از آلیاژ آلومینیوم سبک و بسیار مقاوم به دفرمه شدن',
      'کانکتور دو پین استاندارد هماهنگ با درخت سیم‌کشی فابریک خودرو',
    ],
    featuresEn: [
      'Excellent electrical terminal stability under alternator spikes',
      'Sturdy lightweight aluminum alloy thread resists cold-seizing in steel cases',
      '2-Pin terminal matches factory harness block without adapters',
    ],
    specs: {
      'ولتاژ ورودی': '۹ الی ۱۶ ولت دیسی',
      'نیروی فشرده‌سازی پین': '۱۸ نیوتن نامی',
      'دمای کارکرد مجاز': '-۴۰ تا +۱۲۰ درجه سانتی‌گراد',
    },
    specsEn: {
      'Input Voltage': '9 to 16V DC',
      'Actuation Plunger Force': '18N Nominal',
      'Temperature Range': '-40 to +120 °C',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB253-1-270x262.jpg',
  },
  {
    id: 'AB105',
    title: 'سوئیچ چراغ قرمز مدل AB105',
    titleEn: 'Stop Light Switch AB105',
    model: 'AB105',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'سوئیچ پدال ترمز (چراغ قرمز استپ) خودرو مدل AB105. این قطعه با متریال با دوام و فنربندی استاندارد، کارکرد سریع چراغ‌های خطر عقب را در لحظه فشردن پدال تضمین می‌نماید.',
    descriptionEn: 'Brake pedal stop light switch AB105. Ensuring instantaneous rear brake bulb illumination upon brake pedal movement with long-lasting metal contact nodes.',
    features: [
      'مکانیزم فنری با ضریب سختی بهینه جهت فیدبک لمسی مناسب',
      'جنس پلاتین‌ها از آلیاژ نقره جهت جلوگیری از چسبیدن سوئیچ',
      'بدنه با ساختار فشرده عایق در برابر جرقه‌های القایی سوئیچینگ',
    ],
    featuresEn: [
      'Calibrated return spring coefficient for balanced pedal feel',
      'Silver-alloy contact pads prevent contact fusing and sticking',
      'Dense composite body shell isolates ignition switching spikes',
    ],
    specs: {
      'جریان عبوری نامی': 'حداکثر ۸ آمپر',
      'تعداد پین کانکتور': '۲ فیش فلزی مس-برنج',
      'تست سقوط': 'مقاوم به سقوط آزاد از ارتفاع ۱.۵ متری',
    },
    specsEn: {
      'Rated Shunt Current': 'Max 8 Amps',
      'Terminal Outlets': '2 copper-brass spade lugs',
      'Drop Durability': 'Sustained 1.5m drop test without cracking',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB105-1-1-270x262.jpg',
  },
  {
    id: 'AB244',
    title: 'سوئیچ دوکاره پنل کولر مدل AB244',
    titleEn: 'Double Switch Panel Cooler AB244',
    model: 'AB244',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'سوئیچ کنترل الکترومکانیکی دوکاره پنل کولر خودرو مدل AB244. این قطعه وظیفه قطع و وصل مدار کمپرسور کولر و پاشش گاز مبرد را همزمان با تنظیم دور فن کابین بر عهده دارد.',
    descriptionEn: 'Dual-circuit HVAC control switch AB244. Operates in synchronization with fan speed dials to activate/deactivate the AC compressor and cooling loops.',
    features: [
      'عملکرد روان کلید چرخشی/فشاری با بازخورد لمسی (Haptic Click) عالی',
      'بک‌لایت یکنواخت آبی یخچالی هماهنگ با دمای تهویه مطبوع',
      'عمر طولانی کلیدزنی پلاتین‌های پرسی با روکش نقره',
    ],
    featuresEn: [
      'Smooth rotary/tactile action with distinct luxury haptic clicks',
      'Uniform icy-blue LED backlight matching premium dashboard aesthetics',
      'Extended service life thanks to heavy silver-plated contact rivets',
    ],
    specs: {
      'تعداد مدار مستقل': '۲ کانال برق مجهز',
      'جریان قابل عبور': 'حداکثر ۵ آمپر روی ۱۲ ولت دیسی',
      'تست دمای کارکرد': '-۳۰ تا +۸۵ درجه سانتی‌گراد',
    },
    specsEn: {
      'Independent Circuits': '2 channels',
      'Contact Rating': 'Max 5A / 12V DC',
      'Thermal Endurance': '-30 to +85 °C',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB244-1-270x262.jpg',
  },

  // --- Category: sensors (سنسورها) ---
  {
    id: 'SN101',
    title: 'سنسور موقعیت میل‌لنگ پیشرفته',
    titleEn: 'Advanced Crankshaft Position Sensor SN101',
    model: 'SN101',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور موقعیت میل‌لنگ خودرو مبتنی بر اثر هال با دقت سنجش میکرونی. این سنسور وظیفه پایش دقیق زاویه چرخش میل‌لنگ و ارسال سریع داده‌ها به کامپیوتر خودرو (ECU) جهت هماهنگ‌سازی پاشش سوخت و جرقه‌زنی را دارد.',
    descriptionEn: 'High-precision Hall Effect crankshaft position sensor with sub-micron sensing tolerance. It continuously monitors the RPM and rotation angle of the engine shaft to optimize fuel injection and ignition cycles.',
    features: [
      'مقاومت استثنایی در برابر حرارت شدید موتور تا ۱۵۰ درجه سانتی‌گراد',
      'عدم نویزپذیری الکترومغناطیسی از کویل و کابل‌های برق خودرو',
      'براکت فولادی یکپارچه ضد زنگ با آب‌بندی کامل سیلیکونی اورینگ',
    ],
    featuresEn: [
      'Extreme thermal resistance in hot engine bays up to 150 °C',
      'Robust shielding against EMF noise from coils and power distributors',
      'Integrated heavy stainless steel bracket with premium silicon O-ring',
    ],
    specs: {
      'نوع حسگر': 'سنسور مغناطیسی اثر هال (Hall Effect)',
      'پاسخ فرکانسی': '۰ تا ۱۰ کیلوهرتز',
      'نوع کانکتور': '۳ پین ضدآب با روکش آب‌بندی پلاستیکی',
      'درجه محافظت': 'IP69K (مقاوم در برابر فشار آب و شستشوی کارواش)',
    },
    specsEn: {
      'Sensor Category': 'Magnetic Hall Effect Core',
      'Frequency Response': '0 to 10 kHz',
      'Connector Housing': '3-Pin waterproof automotive plug',
      'IP Rating': 'IP69K (Resists high-pressure washing & steam jets)',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/SN101-1-270x262.jpg',
  },
  {
    id: 'SN102',
    title: 'مپ سنسور فشار مانیفولد (MAP Sensor)',
    titleEn: 'Manifold Absolute Pressure MAP Sensor SN102',
    model: 'SN102',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور فشار مطلق منیفولد گاز و دمای هوای ورودی (Tmap). نقشی حیاتی در محاسبه حجم هوای ورودی به موتور ایفا کرده و ترکیب بهینه سوخت و هوا را برای کاهش مصرف و آلایندگی به ارمغان می‌آورد.',
    descriptionEn: 'Integrated Manifold Absolute Pressure and Temperature sensor (Tmap). Plays a vital role in fuel-ratio calculations by estimating air density entering the cylinder to cut emissions and boost performance.',
    features: [
      'سنجش همزمان فشار منیفولد و دمای هوا در یک سنسور واحد',
      'دقت اندازه‌گیری خطا کمتر از ۱.۵٪ در کل محدوده کاری دما',
      'پایداری بالا در برابر ارتعاشات شدید و حلال‌های نفتی موتور',
    ],
    featuresEn: [
      'Dual sensing arrays in one compact polymer housing',
      'Ultra-precise telemetry with less than 1.5% margin of error',
      'Outstanding physical stability against severe vibration and oily vapors',
    ],
    specs: {
      'رنج سنجش فشار': '۲۰ تا ۲۵۰ کیلو پاسکال',
      'رنج سنجش دما': '-۴۰ تا +۱۳۰ درجه سانتی‌گراد',
      'جریان مصرفی': 'کمتر از ۹ میلی‌آمپر',
      'دقت دمایی': 'حداکثر ۱.۵ درجه خطا',
    },
    specsEn: {
      'Pressure Range': '20 to 250 kPa',
      'Temperature Range': '-40 to +130 °C',
      'Current Consumption': 'Less than 9mA',
      'Temp Accuracy': 'Max 1.5°C tolerance',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/SN102-1-270x262.jpg',
  },
  {
    id: 'AB262',
    title: 'سنسور اکسیژن بالای کاتالیست مدل AB262',
    titleEn: 'Upstream Oxygen Sensor AB262',
    model: 'AB262',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور اکسیژن بالای کاتالیست (Type LSFX سازه پویش Me17) مدل AB262. سنسور اکسیژن (لاندا سنسور) وظیفه پایش دقیق نسبت سوخت به هوا را با ارسال لحظه‌ای میزان غلظت اکسیژن خروجی اگزوز به ECU بر عهده دارد.',
    descriptionEn: 'Advanced planar Upstream Oxygen Lambda Sensor (Type LSFX compatible with Sazeh Pooyesh Me17 ECU system) AB262. It provides closed-loop fuel ratio trimming parameters for lower emissions and peak performance.',
    features: [
      'زمان گرم‌شدن (Light-off) فوق‌العاده کوتاه با هیتر داخلی سرامیکی',
      'مقاومت در برابر بنزین‌های سرب‌دار و سولفور بالا',
      'سیگنال خروجی پایدار با حداقل خطای ولتاژ تفاضلی',
    ],
    featuresEn: [
      'Fast light-off time using an integrated ceramic heating core',
      'Premium chemical resistance against low-grade fuels and sulfur deposits',
      'Highly stable micro-voltage telemetry matching OEM parameters',
    ],
    specs: {
      'سیستم سوخت‌رسانی': 'سازه پویش Me17 (پروژه ایران خودرو و سایپا)',
      'سیم‌های خروجی': '۴ سیم با عایق تفلون و روکش نسوز',
      'دمای کاری مداوم': 'تا ۸۵۰ درجه سانتی‌گراد',
    },
    specsEn: {
      'Engine Management': 'Sazeh Pooyesh Me17 ECU ecosystems',
      'Wire Harness': '4-Wire with pure Teflon insulation and fire-retardant loom',
      'Sustained Exhaust Temp': 'Up to 850 °C',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB262-1-270x262.jpg',
  },
  {
    id: 'AB263',
    title: 'سنسور اکسیژن بالای کاتالیست(SSAT) مدل AB263',
    titleEn: 'Upstream Oxygen Sensor (SSAT) AB263',
    model: 'AB263',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور اکسیژن بالای کاتالیست مجهز به المنت حرارتی ویژه هماهنگ با کامپیوتر خودرو مدل SSAT با دوام مکانیکی بالا.',
    descriptionEn: 'Premium high-speed oxygen sensor calibrated specifically for SSAT electronic fuel injection architectures, featuring exceptional anti-fouling characteristics.',
    features: [
      'عنصر زیرکونیایی ویژه جهت پایش فوری تغییرات گاز اگزوز',
      'پوشش محافظ دولایه نوک سنسور جهت ممانعت از جرم گرفتن سرامیک',
      'بدنه استیل ضد زنگ ۳۰۴ مقاوم در برابر ضربه‌های فیزیکی و شوک حرارتی',
    ],
    featuresEn: [
      'High-purity zirconia element ensuring instant feedback on gas shifts',
      'Double-layer protection shield prevents soot accumulation on the ceramic tip',
      'Grade 304 stainless steel body resists road stone chips and thermal shocks',
    ],
    specs: {
      'پروتکل سنسور': 'لاندا سنسور ولتاژ خروجی ۰ تا ۱ ولت',
      'مقاومت داخلی هیتر': '۹ الی ۱۳ اهم در دمای اتاق',
      'روکش کابل مجهز': 'فایبرگلاس با پوشش سیلیکونی نسوز',
    },
    specsEn: {
      'Output Voltage': 'Standard 0 to 1V Lambda signal',
      'Internal Heater Resistance': '9 to 13 Ohms at room temperature',
      'Cable Loom Protection': 'Heavy fiberglass sleeve with fireproof silicone skin',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB263-1-270x262.jpg',
  },
  {
    id: 'AB254',
    title: 'سنسور ترموکوپل مدل AB254',
    titleEn: 'Thermocouple Sensor AB254',
    model: 'AB254',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور دما ترموکوپلی مدل AB254 جهت پایش مداوم دماهای فوق‌العاده بالا در منیفولد خروجی اگزوز یا توربوشارژر با سرعت پاسخ‌دهی شگفت‌انگیز.',
    descriptionEn: 'High-temperature industrial-grade thermocouple sensor AB254 designed for continuous engine exhaust monitoring and turbocharger health management.',
    features: [
      'سنجش سریع نوسانات دما تا ۱۰۰۰ درجه سانتی‌گراد',
      'سیم غلاف فلزی زره‌دار استیل جهت دفع آسیب‌های فیزیکی و کشش',
      'پایه و رزوه فولادی آب‌بندی ضد نشت دود',
    ],
    featuresEn: [
      'Tracks massive exhaust gas temperature (EGT) spikes up to 1000 °C',
      'Stainless steel braided metal outer mesh prevents pulling or heat damage',
      'Precision welded high-pressure fitting thread ensures zero exhaust leaks',
    ],
    specs: {
      'کلاس ترموکوپل': 'تیپ K صنعتی دقیق',
      'دقت سنجش خطا': 'کمتر از ۱٪ دمای مطلق',
      'رزوه اتصال': 'M10 x 1.0 استاندارد',
    },
    specsEn: {
      'Thermocouple Class': 'Standard High-Accuracy Type-K',
      'Margin of Error': 'Less than 1% of absolute temp reading',
      'Connector Thread': 'M10 x 1.0 standard pitch',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/03/AB254-2-270x262.jpg',
  },
  {
    id: 'AB240',
    title: 'سنسور دمای آب کاربراتور مدل AB240',
    titleEn: 'Carburetor Water Temperature Sensor AB240',
    model: 'AB240',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور سنجش و نمایشگر دمای آب موتورهای نسل قدیمی کاربراتوری مدل AB240 با کالیبراسیون ویژه جهت انطباق با نشانگر تکی داشبورد.',
    descriptionEn: 'Carburetor engine coolant temperature sender AB240. Calibrated to match the resistance parameters of vintage dashboard thermal meters.',
    features: [
      'کنتاکت برنجی تک‌پین با دقت مقاومتی مطلوب',
      'رزوه نصب برنجی مخروطی جهت سهولت آب‌بندی بدون نیاز به نوار تفلون',
      'مقاوم به اکسیداسیون ناشی از ضدیخ‌های اسیدی',
    ],
    featuresEn: [
      'Single-terminal brass connector with linear resistance slope',
      'Conical tapered pipe thread ensures a secure metal-to-metal oil seal',
      'Excellent immunity to electrochemical erosion in old coolant mixtures',
    ],
    specs: {
      'رزوه اتصال': '۱/۸ اینچ NPT مخروطی',
      'رنج مقاومت خروجی': '۲۴۰ اهم تا ۳۳ اهم متغیر',
      'جنس کلاهک سر سنسور': 'باکالیت نسوز',
    },
    specsEn: {
      'Fitting Thread': '1/8" NPT tapered thread',
      'Output Resistance Scope': '240 Ohms (cold) to 33 Ohms (hot)',
      'Insulator Material': 'High-temperature molded Bakelite',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/03/AB240-1-270x262.jpg',
  },
  {
    id: 'AB261',
    title: 'سنسور دمای آب مدل AB261',
    titleEn: 'Water Temperature Sensor AB261',
    model: 'AB261',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور دمای آب خنک‌کننده رادیاتور با مقاومت حرارتی NTC ویژه مدل AB261. ارسال داده‌های فوق‌العاده سریع به کامپیوتر خودرو جهت مدیریت اوبتیمم استارت سرد و پاشش انژکتور.',
    descriptionEn: 'Engine Coolant Temperature (ECT) sensor with NTC thermistor core model AB261. Delivers rapid and stable resistance readouts to prevent cold-start misfires.',
    features: [
      'پاسخ فرکانسی حرارتی (Thermal Time Constant) ناچیز کمتر از ۳ ثانیه',
      'رزین هرمتیک برای ایزولاسیون کامل هسته داخلی در برابر رطوبت مایع خنک‌کننده',
      'کانکتور ترموپلاستیکی فشرده مقاوم در برابر حرارت بالای سرسیلندر',
    ],
    featuresEn: [
      'Fast thermal time constant below 3 seconds for instant ECU updating',
      'Hermetic epoxy seal insulates the internal NTC thermistor from wet acids',
      'Heavy-duty connector block resists melting on hot cylinder blocks',
    ],
    specs: {
      'نوع مقاومت': 'دسی ترمیستور NTC با ضریب منفی دما',
      'دقت اندازه‌گیری مقاومت': '±۱.۵٪ در دمای ۸۰ درجه سانتی‌گراد',
      'رزوه نصب استاندارد': 'M12 x 1.5 مجهز به اورینگ مس',
    },
    specsEn: {
      'Thermistor Core': 'Negative Temperature Coefficient (NTC)',
      'Resistance Tolerance': '±1.5% at 80 °C operational midpoint',
      'Plumbing Size': 'M12 x 1.5 with copper crush washer sealing',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/03/AB261-270x262.jpg',
  },
  {
    id: 'AB114',
    title: 'سنسور دمای آب موتور انژکتوری (زیمنس) مدل AB114',
    titleEn: 'Injector Engine Water Temperature Sensor (Siemens) AB114',
    model: 'AB114',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور سنجش دمای آب موتور با کالیبراسیون استاندارد زیمنس مدل AB114. این سنسور دو فیش نقش مستقیمی در پاشش ایده‌آل سوخت و کارکرد موتور در شرایط سرد زمستانی دارد.',
    descriptionEn: 'ECT (Engine Coolant Temperature) sensor calibrated for Siemens ECU protocols, model AB114. Vital for correct mixture enrichments and cold starts in cold regions.',
    features: [
      'سازگاری کامل با سوکت‌ها و نقشه سیم‌کشی سیستم‌های انژکتور زیمنس',
      'کلاهک پلاستیکی فشرده با خار قفل شو سهولت در تعویض',
      'بدنه تمام فلزی تراشکاری شده از آلیاژ مس با دوام بی‌رقیب',
    ],
    featuresEn: [
      'Full resistance-slope alignment with Siemens ECU firmware profiles',
      'Heavy thermoplastic snap-on locking collar prevents quick disconnections',
      'Precision machined solid brass body ensures maximum durability',
    ],
    specs: {
      'سیستم انژکتور خودرو': 'زیمنس (Siemens) - خودروهای پژو، پراید، سمند',
      'کانکتور اتصال': '۲ فیش پلاستیکی آبی زیمنسی',
      'مقاومت در دمای ۲۰ درجه': 'حدود ۲.۵ کیلو اهم',
    },
    specsEn: {
      'Target Fuel Systems': 'Siemens EMS - Peugeot, Pride, Samand platforms',
      'Wiring Terminals': '2-Pin specialized blue plastic clip connector',
      'Nominal Resistance at 20°C': 'Approx. 2.5 kOhm',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB114-1-270x262.jpg',
  },
  {
    id: 'AB225',
    title: 'سنسور دمای آب موتور مدل AB225',
    titleEn: 'Engine Water Temperature Sensor AB225',
    model: 'AB225',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور سنجش دمای مایع خنک‌کننده موتور مدل AB225 مجهز به ترمیستور NTC با هسته حساس فلزی و آب‌بندی دوبل برای عملکرد در شرایط کاری سخت خودرو.',
    descriptionEn: 'High-reliability Engine Coolant Temperature (ECT) sensor AB225, utilizing a highly responsive NTC core inside a dual-sealed brass tube.',
    features: [
      'اتصال سریع با کلیپس نگهدارنده آب‌بندی ضد نشت',
      'تست مقاومت حرارتی تا دمای ۱۵۰ درجه سانتی‌گراد بدون افت کالیبره',
      'عدم نویزپذیری الکترومغناطیسی از شاسی و سیستم برق خودرو',
    ],
    featuresEn: [
      'Fast-locking safety clip prevents coolant pressure leaks at the flange',
      'Sustained thermal testing up to 150°C with zero resistance calibration drift',
      'Protected internal ground isolates sensory telemetry from electromagnetic noise',
    ],
    specs: {
      'نوع ترمیستور': 'ضریب منفی دمایی NTC با دقت بالا',
      'جریان عبوری کارکرد': 'کمتر از ۵ میلی‌آمپر',
      'رزوه بستن': 'M12 x 1.5 استاندارد',
    },
    specsEn: {
      'Thermistor Grade': 'High-precision negative temperature coefficient (NTC)',
      'Operating Current Draw': 'Less than 5mA',
      'Mounting Thread Pitch': 'M12 x 1.5 standard threading',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB225-270x262.jpg',
  },
  {
    id: 'AB234',
    title: 'سنسور دمای آب موتور مدل AB234',
    titleEn: 'Engine Water Temperature Sensor AB234',
    model: 'AB234',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور حرارتی آب سرسیلندر مدل AB234. این قطعه با متریال با دوام و مقاومت حرارتی ویژه، کارکرد خنک‌سازی موتور را با هدایت دقیق دستور فن‌ها پایش می‌کند.',
    descriptionEn: 'Cylinder head temperature sensor AB234. Designed for deep cylinder block mounting to trigger high/low radiator fan speeds via precise thermal readouts.',
    features: [
      'واشر آب‌بندی مسی ضخیم همراه برای ممانعت از فرار مایع خنک‌کننده',
      'بدنه ساخته شده از برنج مرغوب با ضریب هدایت حرارتی فوق‌العاده',
      'کانکتور دو پین استاندارد هماهنگ با سیستم سیم‌کشی زیمنس و بوش',
    ],
    featuresEn: [
      'Comes with a thick copper crush washer to ensure tight cylinder head seal',
      'Forged from heavy-duty brass for instant thermal tracking',
      '2-Pin standard plug matches various Siemens & Bosch engine wire looms',
    ],
    specs: {
      'رنج دمای پایش': '-۴۰ تا +۱۳۵ درجه سانتی‌گراد',
      'تلرانس اندازه‌گیری': 'حداکثر ±۱ درجه سانتی‌گراد',
      'سوکت اتصال': '۲ پین ضد آب چفت‌شونده',
    },
    specsEn: {
      'Temperature Monitoring Range': '-40 to +135 °C',
      'Sensing Tolerance': 'Max ±1 °C',
      'Output Socket type': '2-Pin locking waterproof connector',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB234-1-270x262.jpg',
  },
  {
    id: 'AB257',
    title: 'سنسور سرعت بلند مدل AB257',
    titleEn: 'High Speed Sensor AB257',
    model: 'AB257',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور سرعت خودرو مدل پایه بلند AB257. این قطعه الکترونیکی وظیفه اندازه‌گیری سرعت خودرو بر مبنای اثر هال و ارسال سیگنال فرکانسی دقیق به آمپرهای جلو و ECU را دارد.',
    descriptionEn: 'High-precision vehicle speed sensor (long shaft edition) AB257. Utilizes an internal Hall Effect chip to read transmission output gear cycles and update the speedometer.',
    features: [
      'شفت پلیمری تقویت شده پایه بلند برای عبور از مجراهای ضخیم پوسته گیربکس',
      'ارسال امواج پالسی مربعی بدون لرزش (Square Wave Signals)',
      'سیم‌پیچ داخلی با دوام با تست عملکردی مداوم',
    ],
    featuresEn: [
      'Extended polymer shaft designed for thick-walled transmission casings',
      'Generates clean square-wave voltage pulses free of signal jitter',
      'Fully enclosed internal wiring protects electromagnetic coils',
    ],
    specs: {
      'پروتکل سنسور': 'مبتنی بر سنسور اثر هال (Hall Effect)',
      'تعداد پالس خروجی': '۸ پالس بر هر دور چرخش شفت',
      'ولتاژ عملکرد تغذیه': '۱۲ ولت DC',
    },
    specsEn: {
      'Sensing Core': 'Hall Effect semiconductor sensor',
      'Pulse Output Frequency': '8 pulses per mechanical shaft revolution',
      'Supply Voltage Requirement': '12V DC nominal power',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB275-1-270x262.jpg',
  },
  {
    id: 'AB256',
    title: 'سنسور سرعت کوتاه مدل AB256',
    titleEn: 'Speed Sensor AB256',
    model: 'AB256',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور سنجش سرعت خودرو پایه کوتاه مدل AB256 جهت پایش لحظه‌ای و با دقت فرکانس خروجی تایرها و دنده‌های دیفرانسیل گیربکس.',
    descriptionEn: 'Short shaft vehicle speed sensor (VSS) AB256. Ideal for space-restricted differential output mountings on compact front-wheel-drive gearboxes.',
    features: [
      'طول شفت کوتاه متراکم متناسب با کارتر و پوسته گیربکس کوچک',
      'بدنه بیرونی پلی‌سیل ضد سایش و ضد حلال‌های صنعتی گیربکس',
      'نصب مستحکم با یک پیچ و چفت کامل اورینگ مجهز',
    ],
    featuresEn: [
      'Ultra-compact short housing is ideal for narrow engine compartment spaces',
      'Poly-composite casing stands up to friction and heavy automatic fluid washes',
      'Simple single-bolt mounting slot with pre-fitted oil seal ring',
    ],
    specs: {
      'نوع پین': '۳ پین آبکاری شده ضد اکسید',
      'جریان مصرفی سنسور': 'کمتر از ۱۲ میلی‌آمپر',
      'رنج فرکانسی پایش': 'تا ۱۲۰۰ هرتز پالس',
    },
    specsEn: {
      'Pins Surface': '3-Pin anti-oxidant electroplated terminals',
      'Supply Current Draw': 'Under 12mA maximum draw',
      'Frequency Tracking Range': 'Up to 1200 Hz clean pulse output',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB256-2-270x262.jpg',
  },
  {
    id: 'AB134',
    title: 'سنسور سرعت مدل AB134',
    titleEn: 'Speed Sensor AB134',
    model: 'AB134',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور سرعت بهینه شده مدل AB134 با بدنه پلیمری متراکم و پورت سوکت سه فیش آب‌بند ضد گرد و خاک و رطوبت کف جاده.',
    descriptionEn: 'Robust Vehicle Speed Sensor (VSS) model AB134, featuring a dense, heavy-duty polymer body and a dust-and-moisture repellent 3-pin connector.',
    features: [
      'دقت اندازه‌گیری سرعت با کمترین میران لرزش عقربه کیلومتر شمار',
      'آب‌بندی کامل بخش‌های داخلی با تکنولوژی تزریق پلاستیک خلأ',
      'عمر مفید فوق‌العاده بالا منطبق با تست‌های مخرب آزمایشگاهی',
    ],
    featuresEn: [
      'Highly precise sensor telemetry completely eliminates dashboard dial jitter',
      'Advanced vacuum-injection molding blocks engine oil seepage into coils',
      'Exceeds strict laboratory life testing constraints for premium reliability',
    ],
    specs: {
      'سیستم محرک خودرو': 'گیربکس‌های دنده‌ای پراید، تیبا و ریو',
      'نوع سیگنال': 'پالس دیجیتال موج مربعی',
      'درجه محافظت': 'IP66 ضد نفوذ',
    },
    specsEn: {
      'Target Platform': 'Manual transmission gears of Pride, Tiba, and Rio',
      'Telemetry Waveform': 'Clean square-wave digital pulse',
      'Enclosure Standard': 'IP66 dust and splash rating',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB134-2-270x262.jpg',
  },
  {
    id: 'AB103',
    title: 'سنسور فشار روغن موتور مدل AB103',
    titleEn: 'Engine Oil Pressure Sensor AB103',
    model: 'AB103',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'فشنگی فشار روغن موتور (روغن‌نما) مدل AB103. قطع و وصل کردن فوری سیگنال چراغ اخطار کمبود فشار روغن موتور جهت جلوگیری از قفل شدن یا یاتاقان زدن موتور.',
    descriptionEn: 'Engine oil pressure switch (sending unit) AB103. Immediately trips the dashboard alert lamp in the event of low oil pressure to prevent catastrophic engine failure.',
    features: [
      'کنتاکت‌های دوبل برنجی مجهز به عایق دی‌الکتریک قوی',
      'بدنه فولادی آبکاری شده مقاوم در برابر اکسیداسیون و نمک پاشی کف خیابان',
      'رزوه نصب با واشر آلومینیومی نسوز',
    ],
    featuresEn: [
      'Double copper terminals backed by heavy-duty dielectric insulating bushings',
      'Sturdy zinc-plated steel body prevents damage from rust and winter road salt',
      'Precisely pitched thread profile complete with high-temperature sealing washer',
    ],
    specs: {
      'رزوه سنسور': 'M10 x 1.0 مخروطی',
      'محدوده فشار تحریک چراغ': '۰.۳ الی ۰.۶ بار (Bar)',
      'جریان عبوری کاری': 'حداکثر ۳ آمپر دیسی',
    },
    specsEn: {
      'Sensor Threading': 'M10 x 1.0 tapered standard',
      'Warning Trip Pressure': '0.3 to 0.6 bar threshold',
      'Rated Shunt Current': 'Max 3 Amps DC load',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB103-1-270x262.jpg',
  },
  {
    id: 'AB107',
    title: 'سنسور فشار روغن موتور مدل AB107',
    titleEn: 'Engine Oil Pressure Sensor AB107',
    model: 'AB107',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور (فشنگی) فشار روغن روان‌کاری موتور مدل AB107 با کالیبره فشار تایید شده بومی جهت پایش مستمر روغن‌کاری میل‌سوپاپ و یاتاقان‌ها.',
    descriptionEn: 'Engine oil pressure warning switch AB107, offering a precise calibrated trigger point to protect valve guides and crank bearings from lubrication failures.',
    features: [
      'مکانیزم دیافراگمی پلیمری فوق‌العاده حساس و مقاوم به روغن‌های ویسکوز بالا',
      'کلاهک متراکم پلیمری آب‌بند ضد رطوبت',
      'پاسخ تماسی مطمئن با کمترین افت کالیبراسیون فشاری',
    ],
    featuresEn: [
      'Ultra-sensitive elastomer diaphragm sustains structural shape in high-viscosity cold oil',
      'Sealed engineering polymer terminal shroud repels engine wash water spray',
      'Calibrated switch action is free of pressure point drift over lifetime',
    ],
    specs: {
      'فشار کارکرد خاموش شدن': 'کمتر از ۰.۴ بار',
      'سایز پیچ نصب': 'M12 x 1.5 هگزاگونال',
      'طول عمر تست هیدرولیک': '۵۰۰,۰۰۰ بار ضربه فشار واسکازین',
    },
    specsEn: {
      'De-actuation Cutoff': 'Under 0.4 bar threshold',
      'Wrench Fastener Size': 'M12 x 1.5 hex base fitting',
      'Cyclic Impulse Life': '500,000 high-pressure oil cycles',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB107-1-1-270x262.jpg',
  },
  {
    id: 'AB128',
    title: 'سنسور فشار روغن موتور مدل AB128',
    titleEn: 'Engine Oil Pressure Sensor AB128',
    model: 'AB128',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور فشار روغن موتور خودروهای سواری مدل AB128 با واشر آب‌بندی تفلونی فابریک و عایق کامل در برابر لرزش‌های شدید بلوک سیلندر.',
    descriptionEn: 'High-durability engine oil pressure sensor switch AB128, pre-equipped with Teflon sealing tapes and vibration insulation.',
    features: [
      'بدنه ساخته شده با فرآیند آهنگری سرد جهت افزایش چشمگیر مقاومت فشاری بدنه',
      'کنتاکت‌های برنجی با فنریت عالی و رسانایی پایدار',
      'روکش سر سرامیکی با مقاومت در برابر دماهای مفرط بالای موتور',
    ],
    featuresEn: [
      'Cold-forged steel shell provides exceptional safety margins against bursting',
      'Fatigue-resistant copper internal springs keep contacts perfectly aligned',
      'Ceramic terminal core prevents melting or cracking under blistering block temps',
    ],
    specs: {
      'سایز رزوه پیچ': 'M10 x 1.0 متریک',
      'ولتاژ عملکرد مجاز': '۶ الی ۲۴ ولت DC',
      'فشار قطع چراغ روغن': '۰.۵ بار',
    },
    specsEn: {
      'Thread Size': 'Metric M10 x 1.0',
      'Operating Voltage Scope': '6V to 24V DC broad grid range',
      'Light Shutoff Pressure': '0.5 bar limit',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/Untitled-128-270x262.jpg',
  },
  {
    id: 'AB151',
    title: 'سنسور فشار روغن موتور مدل AB151',
    titleEn: 'Engine Oil Pressure Sensor AB151',
    model: 'AB151',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'فشنگی و سنسور پایش فشار روغن روانکاری پمپ روغن (اویل پمپ) مدل AB151 جهت رصد مستمر چرخه سلامت موتور.',
    descriptionEn: 'Engine oil pump pressure sender unit AB151, engineered to monitor oil galley lines for instant drop updates.',
    features: [
      'عنصر فشاری دیافراگمی با مقاومت کششی بالا',
      'مقاومت کامل در برابر خوردگی اسیدی ناشی از روغن‌های کهنه کارکرده',
      'اتصال الکتریکی پایدار با سیم‌های قلع‌اندود شده ضد زنگ',
    ],
    featuresEn: [
      'High-tensile composite diaphragm retains flexibility under freezing cold',
      'Anti-corrosive metal housing resists chemical attack by soot-loaded old oil',
      'Rust-proof tinned copper wire connectors ensure clear analog signaling',
    ],
    specs: {
      'رزوه دنده‌ای': 'M10 x 1.25',
      'فشار تحریک سیگنال': '۰.۴۵ بار',
      'مقاومت تماسی سوئیچ': 'کمتر از ۴۰ میلی اهم',
    },
    specsEn: {
      'Threading Configuration': 'M10 x 1.25 metric pitch',
      'Galley Pressure Trip': '0.45 bar nominal setting',
      'Switch Connection Ohm': 'Less than 40 mOhm contact resistance',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB151-1-270x262.jpg',
  },
  {
    id: 'AB224',
    title: 'سنسور فشار روغن موتور مدل AB224',
    titleEn: 'Engine Oil Pressure Sensor AB224',
    model: 'AB224',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'فشنگی فشار روغن موتور هماهنگ با سیستم‌های مدیریت برق و ECU نسل جدید خودروها مدل AB224 با تلرانس فشار خطا بسیار کم.',
    descriptionEn: 'Modern electronic engine oil pressure sensor switch AB224, holding extremely tight tolerance limits to feed real-time oil indicators.',
    features: [
      'آب‌بندی با واشر تخت فلزی برنجی مس کوب شده',
      'بدنه بیرونی استوانه‌ای فشرده هگزاگونال برای بستن آچار آسان',
      'اتصال کانکتوری قفل شو ضدآب فابریک',
    ],
    featuresEn: [
      'Packed with copper-clad crash rings for leak-free high-pressure installation',
      'Compact hexagonal steel envelope facilitates easy installation with standard tools',
      'Double-latch terminal slot holds watertight seals in extreme engine washes',
    ],
    specs: {
      'رنج مجاز فشار مجاز واسکازین': '۰ تا ۱۰ بار',
      'ولتاژ منبع تغذیه': '۱۲ ولت DC',
      'دقت سوئیچ تماسی': '±۰.۰۵ بار',
    },
    specsEn: {
      'Sustained Fluid Pressure': '0 to 10 bar maximum',
      'Nominal Grid Voltage': '12V DC',
      'Trigger Point Tolerance': 'Within ±0.05 bar deviation limits',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB224-270x262.jpg',
  },
  {
    id: 'AB258',
    title: 'سنسور فشار روغن موتور مدل AB258',
    titleEn: 'Engine Oil Pressure Sensor AB258',
    model: 'AB258',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور فشار سنجی اویل‌پمپ پیشرفته مدل AB258 با پین اتصال مس طلاکاری شده برای سرعت انتقال عالی پالس برق به صفحه کیلومترشمار.',
    descriptionEn: 'Advanced engine oil pressure warning switch AB258. Features high-performance gold-plated connector tabs for instantaneous electrical grounding.',
    features: [
      'بدنه ساخته شده با استنلس استیل ۳۱۶ فشرده مستحکم',
      'دیافراگم فلزی مستحکم داخلی جهت دوام و دقت در میلیون‌ها بار استفاده',
      'مقاومت کامل عایقی در برابر نفوذ رطوبت و گریس',
    ],
    featuresEn: [
      'Precision machined from high-grade marine 316 stainless steel',
      'Metal-membrane core sustains calibration accuracy across millions of cycles',
      'Advanced vulcanized seal prevents oil bypass leaks into terminal plug',
    ],
    specs: {
      'رزوه نصب سنسور': 'M14 x 1.5 متریک',
      'فشار قطع سوئیچ': '۰.۴ بار نامی',
      'جریان عبوری استارت': 'کمتر از ۲ آمپر دیسی',
    },
    specsEn: {
      'Base Thread Pitch': 'Metric M14 x 1.5 standard fitting',
      'Switch Contact Opening': '0.4 bar nominal target',
      'Rated Electrical Current': 'Under 2 Amps DC loop',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB258-2-270x262.jpg',
  },
  {
    id: 'AB180',
    title: 'سنسور فشار روغن موتور ملی مدل AB180',
    titleEn: 'National Engine Oil Pressure Sensor AB180',
    model: 'AB180',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'فشنگی فشار روغن موتور ملی EF7 مدل AB180. این قطعه به صورت ویژه برای موتورهای پرقدرت ملی کالیبره شده و فشار روغن تغذیه سیستم تایمینگ متغیر سوپاپ‌ها (CVVT) را پایش می‌کند.',
    descriptionEn: 'National EF7 engine oil pressure sensor switch AB180. Calibrated for the national double-overhead-cam engine, ensuring correct oil pressure triggers for the CVVT solenoid.',
    features: [
      'موتور خودروی هدف: سمند، دنا و تارا مجهز به موتور ملی EF7',
      'مقاومت حرارتی بالا متناسب با گرمای شدید موتور توربوشارژر دنا پلاس',
      'آب‌بندی رزوه فلزی هرمتیک برای ممانعت کامل از نشت روغن به سرسیلندر',
    ],
    featuresEn: [
      'Compatible Engines: Samand, Dena, Tara equipped with EF7 / EF7 Turbo',
      'Extreme thermal resistance suited for high exhaust temperatures of EF7 TC',
      'Hermetically welded threads prevent block-oil leakage onto the harness loom',
    ],
    specs: {
      'کد فنی قطعه': 'AB180',
      'رزوه نصب قطعه': 'M12 x 1.5 متریک مخروطی',
      'نقطه تحریک سنسور': '۰.۵۵ بار',
    },
    specsEn: {
      'Part Identifier': 'AB180',
      'Thread Fitting Spec': 'Metric M12 x 1.5 tapered design',
      'Warning Alarm Setting': '0.55 bar precision trip point',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB180-1-2-270x262.jpg',
  },
  {
    id: 'AB238',
    title: 'سنسور فشار روغن هیدرولیک فرمان مدل AB238',
    titleEn: 'Steering Hydraulic Oil Pressure Sensor AB238',
    model: 'AB238',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور (فشنگی) فشار هیدرولیک جعبه فرمان مدل AB238. ارسال سیگنال فشار هیدرولیک به ECU جهت بالا بردن جزئی دور آرام موتور هنگام چرخش فرمان در جا، برای جلوگیری از افت دور و لرزش موتور.',
    descriptionEn: 'Power steering hydraulic oil pressure switch AB238. Sends hydraulic pressure signals to the engine ECU, enabling idle-up compensation to prevent engine stall or vibration when steering at idle.',
    features: [
      'دیافراگم فولاد آلیاژی مستحکم برای پایداری در فشارهای بسیار بالای پمپ هیدرولیک تا ۱۲۰ بار',
      'سوکت چسبنده با عایق‌بندی کامل در برابر هیدرولیک خورنده فرمان',
      'عملکرد مکانیکی مینیاتوری دقیق با پاسخ دهی آنی',
    ],
    featuresEn: [
      'Heavy-duty alloy-steel diaphragm handles power steering fluid spikes up to 120 bar',
      'Fully molded nylon neck prevents transmission fluid bypass into the wire harness',
      'Micro-mechanical switch design provides instantaneous response times under cornering',
    ],
    specs: {
      'رزوه اتصال لوله هیدرولیک': 'M10 x 1.25 متریک',
      'رنج فشار قطع و وصل': '۲۵ تا ۳۵ بار فعال‌سازی',
      'حداکثر فشار هیدرولیک تحمل': '۱۴۰ بار',
    },
    specsEn: {
      'Hydraulic Union Size': 'Metric M10 x 1.25',
      'Toggling Threshold': '25 to 35 bar activation range',
      'Maximum Burst Safety': '140 bar structural rating',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB238-270x262.jpg',
  },
  {
    id: 'AB243',
    title: 'سنسور کنترل دمای فن مدل AB243',
    titleEn: 'Fan Temperature Control Sensor AB243',
    model: 'AB243',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'فشنگی و سنسور کنترل قطع و وصل دمایی رله فن خنک‌کننده رادیاتور مدل AB243 جهت کارکرد ایده‌آل موتور در دماهای گرم تابستانی و هنگام زیر بار رفتن با کولر.',
    descriptionEn: 'ECT thermal switch for radiator cooling fan control, model AB243. Regulates engine temperatures during extreme summer heat or highway loads.',
    features: [
      'مخزن سنسور مسی سنگین با بالاترین انتقال حرارت به بابل‌متال داخلی',
      'بسته بندی کامل رزوه با آلیاژ مس نسوز',
      'پایداری فوق‌العاده در برابر نمک‌پاشی و اسیدهای خنک‌کننده رادیات',
    ],
    featuresEn: [
      'Heavy duty copper casing ensures fastest thermal pickup from coolant fluid',
      'Shipped with highly durable heat-proof copper gasket rings',
      'Extremely resistant to ethylene-glycol acid breakdown products inside radiators',
    ],
    specs: {
      'دمای کارکرد قطع سوئیچ': '۹۲ درجه سانتی‌گراد',
      'دمای وصل سوئیچ مجدد': '۸۷ درجه سانتی‌گراد',
      'جریان عبوری پلاتین': 'حداکثر ۱۵ آمپر دیسی روی ۱۲ ولت',
    },
    specsEn: {
      'Opening Temperature Target': '92 °C',
      'Closing Temperature Target': '87 °C',
      'Continuous Switching Limit': 'Max 15A / 12V DC load',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB243-2-270x262.jpg',
  },
  {
    id: 'AB108',
    title: 'سنسور نمایشگر درجه آب موتور انژکتوری مدل AB108',
    titleEn: 'Injector Engine Water Temp Gauge Sensor AB108',
    model: 'AB108',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'فشنگی تک فیش دمای آب (نمایشگر آمپر کیلومتر) خودروهای انژکتوری مدل AB108 با بدنه برنجی تراشکاری شده دقیق جهت هدایت بی‌نقص عقربه دمای آب داشبورد.',
    descriptionEn: 'Single-terminal engine coolant temperature (ECT) sender unit AB108, designed to send precise resistive analog values to the cabin temp gauge.',
    features: [
      'هسته NTC ترمیستوری با پاسخ مقاومتی کاملاً خطی و کالیبره',
      'جنس پایه برنج آلیاژی با ترش‌کاری فوق‌العاده دقیق',
      'اتصال فیش برنجی پرچی مقاوم در برابر زنگ زدگی و لرزش',
    ],
    featuresEn: [
      'High-grade NTC thermistor element delivers precise, linear gauge needle travel',
      'Sized and machined from supreme industrial brass stock for absolute thread precision',
      'Heavy-duty brass spade terminal terminal stands up to heat cycle vibration',
    ],
    specs: {
      'نوع کانکتور خروجی': 'تک فیش مس تخت (Spade terminal)',
      'سیستم سیم‌کشی': 'انژکتوری پژو ۴۰۵، پارس و سمند',
      'تلرانس آمپر': 'کمتر از ۲٪ خطا',
    },
    specsEn: {
      'Connector Layout': 'Single flat brass male spade terminal',
      'Target Platforms': 'Peugeot 405, Pars, and Samand injection wiring systems',
      'Resistive Deviation': 'Within 2% total resistance margin',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB108-1-270x262.jpg',
  },
  {
    id: 'AB109',
    title: 'سنسور نمایشگر درجه آب موتور( ترموکوپل) مدل AB109',
    titleEn: 'Engine Water Temp Gauge Sensor (Thermocouple) AB109',
    model: 'AB109',
    category: 'sensors',
    categoryFa: 'سنسور ها',
    categoryEn: 'Sensors',
    description: 'سنسور پیشرفته و مجهز به مکانیزم مینیاتوری ترموکوپلی دمای آب موتور مدل AB109 با آب‌بندی سرامیکی ضد فرار فشار مایعات در داخل سرسیلندر.',
    descriptionEn: 'Engine cooling water temperature gauge sensor utilizing a thermocouple mechanism, model AB109. Ceramic insulation guarantees bulletproof sealing.',
    features: [
      'ترموکوپل حساس کروم-آلومل داخلی برای پایش فوق‌العاده سریع دمای آب',
      'مقاومت کامل در برابر زنگ‌زدگی و رسوبات آهکی آب رادیاتور',
      'طول بدنه بهینه شده جهت انطباق با مجرای رادیاتورهای نسل جدید',
    ],
    featuresEn: [
      'Highly sensitive internal nickel-alloy thermocouple ensures fastest telemetry feedback',
      'Heavy plated protective sleeve resists mineral scaling and lime deposits in the cooling jacket',
      'Perfectly balanced insert probe matches standard water flanges of modern radiators',
    ],
    specs: {
      'رزوه نصب فلزی': 'M10 x 1.0 متریک',
      'رنج مجاز پایش حرارت': '۰ تا ۱۵۰ درجه سانتی‌گراد',
      'آب‌بندی ترمو پلاستیکی': 'سرامیک-اپوکسی نسوز',
    },
    specsEn: {
      'Fitting Thread Size': 'Metric M10 x 1.0',
      'Heat Tracking Scale': '0 to 150 °C operational scale',
      'Epoxy Insulation Barrier': 'Ceramic-epoxy fireproof high-density shield',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB109-2-270x262.jpg',
  },

  // --- Category: switches (سوئیچ‌ها - دنده عقب و چراغ استپ و ...) ---
  {
    id: 'SW201',
    title: 'سوئیچ پدال ترمز چهار فیش مجهز',
    titleEn: 'Brake Pedal Multi-Switch (4-Pin) SW201',
    model: 'SW201',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'سوئیچ چراغ استپ ترمز متصل به پدال ترمز خودرو. این سوئیچ وظیفه حیاتی روشن کردن چراغ‌های ترمز عقب و همزمان قطع مدار کروز کنترل و ارسال سیگنال ترمزگیری به ECU موتور و سیستم ABS را بر عهده دارد.',
    descriptionEn: 'High-power brake light switch attached directly to the pedal. It holds dual channels: one triggers rear stoplights, while the other disengages Cruise Control and updates the ABS/ECU registers.',
    features: [
      'عملکرد همزمان دو کنتاکت قطع و وصل مستقل (کروز کنترل و استپ چراغ)',
      'تنظیم خودکار طول پین فشاری جهت نصب آسان روی انواع پدال‌ها',
      'کنتاکت‌های آلیاژ نقره جهت جلوگیری از خال‌زدگی و پایداری رسانایی الکتریکی',
    ],
    featuresEn: [
      'Simultaneous dual contacts for stoplights (NO) and Cruise Control (NC)',
      'Self-adjusting plunger travel length for generic mounting on pedals',
      'Silver-alloy contacts preventing arcing and maintaining stable low resistance',
    ],
    specs: {
      'پیکربندی کلید': 'کنتاکت دوبل (NC + NO)',
      'جریان کاری ماکزیمم': '۱۰ آمپر روی ۱۲ ولت دیسی',
      'طول عمر کلیدزنی': 'بیش از ۵۰۰,۰۰۰ بار فشرده شدن',
      'نیروی عملکردی فشاری': '۱۵ الی ۲۵ نیوتن',
    },
    specsEn: {
      'Circuit Toggling': 'Double Contacts (NC + NO)',
      'Max Rating': '10A / 12V DC',
      'Toggling Lifetime': 'Over 500,000 pedal push cycles',
      'Operating Force': '15 to 25 N',
    },
    image: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'SW202',
    title: 'سوئیچ لای دری ضدآب خودرو',
    titleEn: 'Waterproof Car Door Switch SW202',
    model: 'SW202',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'سوئیچ لای درپوش‌ها و درب‌های خودرو با آب‌بندی لاستیکی ویژه جهت جلوگیری از نفوذ باران و گرد و خاک. ارسال سیگنال قفل یا باز بودن درب‌ها به سیستم صوتی هشدار و نمایشگر پشت آمپر.',
    descriptionEn: 'Heavy-duty automotive door jamb switch encased in dense rubber sealing to repel water and grime. It reports real-time open/close states to warning buzzers and cluster panels.',
    features: [
      'روکش منعطف باکیفیت از جنس لاستیک EPDM مقاوم در برابر ازون و اشعه UV',
      'فنر استنلس استیل با مقاومت در برابر زنگ‌زدگی در مرطوب‌ترین مناطق کشور',
      'اتصال ایمن زمین بدنه با پیچ نصب',
    ],
    featuresEn: [
      'Highly flexible outer casing made of premium UV/ozone proof EPDM rubber',
      'Stainless steel spring resistant to oxidation in humid geographical zones',
      'Secure chassis ground connection integrated directly with the mounting screw',
    ],
    specs: {
      'نوع مدار': 'تک‌پل با اتصال زمین بدنه',
      'مقاومت تماسی': 'کمتر از ۵۰ میلی اهم',
      'دمای کارکرد': '-۳۵ تا +۸۰ درجه سانتی‌گراد',
      'طول عمر': '۳۰۰,۰۰۰ سیکل',
    },
    specsEn: {
      'Circuit Link': 'Single-Pole with direct body grounding',
      'Contact Resistance': 'Less than 50 mOhm',
      'Working Range': '-35 to +80 °C',
      'Durability': '300,000 cycles',
    },
    image: 'https://images.unsplash.com/photo-1558441719-ff34b0524a24?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'AB027',
    title: 'سوئیچ چراغ دنده عقب مدل AB027',
    titleEn: 'Reverse Light Switch AB027',
    model: 'AB027',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'فشنگی چراغ دنده عقب گیربکس اتومبیل مدل AB027 با کانکتور پلیمری آب‌بند ضد گرد و خاک و اتصال هگزاگونال آبکاری شده مقاوم.',
    descriptionEn: 'Automotive reverse lamp switch AB027 featuring a robust quick-connect socket layout, preventing dust, water, and road grime from reaching electrical connections.',
    features: [
      'کانکتور پلاستیکی عایق با خار قفل‌شونده برای اطمینان اتصالات برقی',
      'پایه رزوه فولادی مستحکم آب‌بندی ضد نشت واسکازین',
      'طول عمر مکانیکی و پایداری عملکرد در تغییرات ناگهانی دنده',
    ],
    featuresEn: [
      'Sealed quick-connect housing with integrated dual retaining clips',
      'Precision brass threads prevent manual transmission fluid leaks',
      'Ensures reliable electrical grounding even after heavy shifting',
    ],
    specs: {
      'سایز پیچ رزوه': 'M12 x 1.5',
      'ولتاژ عملکرد': '۱۲ ولت DC',
      'جریان عبوری': '۶ آمپر',
    },
    specsEn: {
      'Thread Dimensions': 'M12 x 1.5',
      'Operating Voltage': '12V DC',
      'Rated Current Limit': '6 Amps',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB027-1-270x262.jpg',
  },
  {
    id: 'AB052',
    title: 'سوئیچ چراغ دنده عقب مدل AB052',
    titleEn: 'Reverse Light Switch AB052',
    model: 'AB052',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'فشنگی دنده عقب دابل-آب‌بند مدل AB052. مقاومت کامل در برابر روغن گیربکس داغ و انتقال سیگنال روان و بی‌وقفه به چراغ‌ها و سوییچ‌های هماهنگ با سنسورهای کمکی پارک.',
    descriptionEn: 'Double-sealed reverse switch AB052. Specially formulated to resist boiling-hot gear oils while delivering uninterrupted signals to backup cameras.',
    features: [
      'واشر آب‌بندی داخلی دوبل ویتون با مقاومت در برابر خورندگی شیمیایی روغن',
      'پین‌های داخلی نقره کبالت ضد جرقه جهت افزایش خارق‌العاده ایمنی سوئیچ',
      'سازگاری با دامنه وسیع ولتاژهای کاری خودرو',
    ],
    featuresEn: [
      'Double Viton internal seals prevent high-pressure oil bypass leaks',
      'Spark-suppressed silver-cobalt internal contact buttons for safety',
      'Compatible with broad automotive electrical grids from 9 to 18V DC',
    ],
    specs: {
      'سایز دنده رزوه': 'M12 x 1.25',
      'مقاومت عایق تماسی': 'کمتر از ۵۰ میلی اهم',
      'فشار هیدرولیک تحمل': 'تا ۱۵ بار بدون دفرمه شدن',
    },
    specsEn: {
      'Thread Pitch Size': 'M12 x 1.25',
      'Contact Resistance': 'Less than 50 mOhm',
      'Hydrostatic Safety Pressure': 'Up to 15 bar backpressure resistance',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB052-1-270x262.jpg',
  },
  {
    id: 'AB227',
    title: 'سوئیچ چراغ دنده عقب مدل AB227',
    titleEn: 'Reverse Light Switch AB227',
    model: 'AB227',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'سوئیچ و فشنگی دنده عقب مدل AB227 با عایق‌بندی ضد نشت واسکازین و کانکتور فابریک خودروهای ایرانی و فرانسوی.',
    descriptionEn: 'High-durability reverse light switch AB227. Hermetically sealed trigger switch with a ball-plunger configuration designed for manual transmissions.',
    features: [
      'مکانیزم ماشه کروی (Ball Plunger) سخت‌کاری شده جهت کاهش استهلاک',
      'عایق پلیمری یکپارچه پورت‌ها برای عدم نفوذ رطوبت و گریس',
      'بدنه ساخته شده از آلیاژ آلومینیوم فشرده و نشکن',
    ],
    featuresEn: [
      'Ball-plunger actuator minimizes shift fork drag and physical wear',
      'Molded terminal housing protects pins from vibration and road impacts',
      'Robust and compact aluminum alloy thread structure',
    ],
    specs: {
      'ولتاژ عملکرد': '۱۲ ولت DC',
      'جریان عبوری کاری': 'حداکثر ۱۰ آمپر دیسی',
      'درجه محافظت کانکتور': 'IP67 ضدآب کامل',
    },
    specsEn: {
      'Operating Voltage': '12V DC',
      'Rated Current Limit': 'Max 10A DC',
      'Ingress Protection': 'IP67 waterproof rating',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB227-1-270x262.jpg',
  },
  {
    id: 'AB253',
    title: 'سوئیچ چراغ دنده عقب مدل AB253',
    titleEn: 'Reverse Light Switch AB253',
    model: 'AB253',
    category: 'switches',
    categoryFa: 'سوئیچ ها',
    categoryEn: 'Switches',
    description: 'سوئیچ چراغ دنده عقب فابریک مدل AB253 با پین اتصال مس دو فیش استاندارد و کالیبراسیون دقیق برقی.',
    descriptionEn: 'Highly responsive reverse gear sensor switch AB253, specifically designed for national and French manual transmissions.',
    features: [
      'پایداری فوق‌العاده کنتاکت‌های برقی در نوسانات شدید ولتاژ دینام',
      'بدنه ساخته شده از آلیاژ آلومینیوم سبک و بسیار مقاوم به دفرمه شدن',
      'کانکتور دو پین استاندارد هماهنگ با سیم‌کشی فابریک خودرو',
    ],
    featuresEn: [
      'Excellent electrical terminal stability under alternator spikes',
      'Sturdy lightweight aluminum alloy thread resists gearbox casing friction',
      '2-Pin terminal matches factory harness block without adapters',
    ],
    specs: {
      'ولتاژ ورودی': '۹ الی ۱۶ ولت دیسی',
      'نیروی فشرده‌سازی پین': '۱۸ نیوتن نامی',
      'دمای کارکرد مجاز': '-۴۰ تا +۱۲۰ درجه سانتی‌گراد',
    },
    specsEn: {
      'Input Voltage': '9 to 16V DC',
      'Actuation Plunger Force': '18N Nominal',
      'Temperature Range': '-40 to +120 °C',
    },
    image: 'https://imantak.com/wp-content/uploads/2024/01/AB253-1-270x262.jpg',
  }
];
